global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "llm-gateway"
    static_configs:
      - targets: ["gateway:8000"]
    metrics_path: /metrics

  - job_name: "node-exporter"
    static_configs:
      - targets:
          - "10.208.211.62:9100"
          - "10.208.211.54:9100"
          - "10.208.211.59:9100"
          - "10.208.211.64:9100"

  - job_name: "nvidia-gpu-exporter"
    static_configs:
      - targets:
          - "10.208.211.62:9835"
          - "10.208.211.54:9835"
          - "10.208.211.59:9835"
          - "10.208.211.64:9835"

  - job_name: "llama-cpp"
    static_configs:
      - targets:
          - "10.208.211.62:8080"
          - "10.208.211.54:8080"
          - "10.208.211.59:8080"
          - "10.208.211.64:8080"
    metrics_path: /metrics
